### ISSUE TITLE
Folder and file names should be lower case

### ISSUE THREAD

**Issue by ClementPernet** [linbox-team/linbox#6]
to avoid confusion when porting on a case insensitive file systems.

**Comment by ClementPernet** [comment]
Fixed the issue for directories in 5bd736

**Comment by bdsaunders** [comment]
Clément, Thanks for that.

A related issue:  NTL has it's headers in include/NTL/  rather than
include/ntl/.  We refer to the latter in some places: "#include
<ntl/tools.h>".
I suppose here we must use the Caps per NTL rather than changing the NTL
install process.

I see the CamelCap directories still exist, largely emptied.  Do you intend
to remove them later?

What about Caps in file names such as
ring/PID-ntl-zz_p.h  ring/PIR-modular-int32.h  ring/PIR-ntl-ZZ_p.h
Clément?
I'd be willing to take them out, but it will require a little adjustment to
our conventions inasmuch as zz and ZZ are an important difference in NTL
and also I don't want to write p-i-d-..., which is according to our
convention, strictly construed.

-dave

**Comment by ClementPernet** [comment]
Indeed, we should keep using the upper case NTL folder names when they are the ones of the NTL library. I tried to avoid fixing them, but failed to do so. Thanks for reverting these ones.

As for the still existing CamelCase folders, they are no longer versionned and git probably let them on your file system, because they contained unversionned files (Makefile.in Makefile, etc). You should be free to rm them.

Next step is to remove caps names in filenames too.

I wouldn't mind having `pid-integer.h` instead of `p-i-d-integer.h`

I'm not familiar with NTL is there actually a difference between zz and ZZ in file names there? Does it impact us if we decide to move everything to lower case?

**Comment by bdsaunders** [comment]
Actually in NTL the usage in file names is lzz (wordsize ints) and ZZ (big
ints).  I'll move the file names on our related files to lower case and use
lzz and zz where appropriate to make this distinction.
